---
  - include_vars: "{{ playbook_dir }}/config.yml"      
  - include_vars: "main.yml"

  - name: Update system
    apt:
      name: '*'
      state: 'latest'
      update_cache: yes
    retries: 300
    delay: 10

  - name: Reboot after update  
    reboot:
      msg: Reboot triggered
      reboot_timeout: 360
