apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: user-grafana
  name: user-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-grafana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: user-grafana
    spec:
      containers:
      - env:
        - name: GF_AUTH_PROXY_AUTO_SIGN_UP
          value: "false"
        - name: GF_AUTH_PROXY_ENABLED
          value: "true"
        - name: GF_AUTH_PROXY_HEADER_NAME
          value: X-WEBAUTH-USER
        - name: GF_AUTH_PROXY_HEADER_PROPERTY
          value: username
        - name: GF_SERVER_ROOT_URL
          value: /grafana
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
        - name: GF_USERS_AUTO_ASSIGN_ORG
          value: "false"
        image: grafana/grafana:6.6.2
        imagePullPolicy: ""
        name: user-grafana
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: user-grafana
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: user-grafana
        persistentVolumeClaim:
          claimName: user-grafana
status: {}
