apiVersion: v1
kind: ConfigMap
metadata:  
  labels:
    app: metrics-config
    chart: metrics-2.3.2
    heritage: Tiller
    release: metrics-config
  name: metrics-config
  namespace: default
  resourceVersion: "2575"
  selfLink: /api/v1/namespaces/orc8r/configmaps/metrics-config
  
data:
  prometheus.yml: |-
    global:
      scrape_interval:     15s # By default, scrape targets every 15 seconds.
      evaluation_interval: 15s # By default, scrape targets every 15 seconds.
      external_labels:
        monitor: 'master'

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: "magma_pushgateway"
        honor_labels: true
        metric_relabel_configs:
          - regex: 'job'
            action: labeldrop
          - regex: 'instance'
            action: labeldrop
        static_configs:
          - targets: ['prometheus-cache:9091']

    rule_files:
      - '/etc/prometheus/alert_rules/*_rules.yml'

    alerting:
      alertmanagers:
        - scheme: http
          static_configs:
            - targets: ['alertmanager:9093']

  alertmanager.yml: |-
    global:
      resolve_timeout: 5m
      http_config: {}
      smtp_hello: localhost
      smtp_require_tls: true
      pagerduty_url: https://events.pagerduty.com/v2/enqueue
      opsgenie_api_url: https://api.opsgenie.com/
      wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
      victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
    route:
      receiver: null_receiver
      group_by:
      - alertname
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
    receivers:
    - name: null_receiver
    templates: []

