apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-configurer-claim0
  labels:
    type: local
spec:  
  capacity:
    storage: 100Mi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: prometheus-configurer-claim0
    namespace: default    
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/k8s_volume/prometheus-configurer-claim0
    server: {{ .Values.nfs.ip }}
