apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: prometheus-configurer
  name: prometheus-configurer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prometheus-configurer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: prometheus-configurer
    spec:
      containers:
      - args:
        - -port=9100
        - -rules-dir=/etc/configs/alert_rules
        - -prometheusURL=prometheus:9090
        - -multitenant-label=networkID
        - -restrict-queries
        image: facebookincubator/prometheus-configurer:1.0.0
        imagePullPolicy: ""
        name: prometheus-configurer
        resources: {}
        volumeMounts:
        - mountPath: /etc/configs
          name: prometheus-configurer-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: prometheus-configurer-claim0
        persistentVolumeClaim:
          claimName: prometheus-configurer-claim0
      imagePullSecrets:
      - name: regcred
status: {}
