apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: psql
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-02-12T23:02:16Z"
  labels:
    app.kubernetes.io/instance: psql
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.2.7
  name: {{ .Values.psql.name }}
  namespace: default
spec:
  ports:
  - name: tcp-postgresql
    port: 5432
    protocol: TCP
    targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/instance: psql
    app.kubernetes.io/name: postgresql
    role: primary
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
