
- include_vars: "{{ playbook_dir }}/config.yml"      
- include_vars: "main.yml"
   
- name: Replace sources.list
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'

- name: Update cache
  apt:
    update_cache: yes
    
- name: Upgrade
  apt:
    upgrade: dist

  - name: Update system
    apt:
      name: '*'
      update_cache: yes
      state: 'latest'

  - name: Reboot after update  
    reboot:
      msg: Reboot triggered
      reboot_timeout: 360