# Define enviroment
- hosts: localhost
  roles:     
    - role: 01_define_enviroment  

# Clear everything
- hosts: hypervisor
  user: cloud
  become: true
  roles:     
    - role: 02_remove_all

# Create everything
- hosts: hypervisor
  user: cloud
  become: true
  roles:     
    - role: 04_create_vms

# Update nodes:
- hosts: nodes
  user: debian
  become: true
  roles:     
    - role: 05_update
