---

  pw_hash: $6$SEaggDjiCCX4Togw$Ywp6LEk0MCA1Axl7xQj78CXCOH2JDn1YAahqqZ4DH21GMZueTqT5LisIaCzES.0UjZfUFg/qngHgtum2INXNH1
  # To generate a password hash:
  # python3 -c 'import crypt; import os; print(crypt.crypt("password123", crypt.mksalt(crypt.METHOD_SHA512)))'

  authorized_keys: 
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4tzrayU6ahMhmWuicy+oFfy//9oB+2EdbbmDfA0d+k3SpYjWVqho64/L+sQIAN0RGBJx42GkbKi8B6AriPw8omLOCk2WSYW3ymEC7n3l32M5T4cLr8LIYwoMOBZkMtRc3H62PrHgDoTJLhUOvT2ewj1SLl7iU5gQuInwPE6jWooIb8R6KMUl31qNpkafCVPz5ovw0iYbDamHQF6sq081Xl39px2345T8TofIAocyBUfCOstmAvPaD9lXIV3j9JmPhAy0oweXpxdPiQzBHXepLh/jrvHrV5ggl2iwmLgF3uzwYdFlQN6eCniBtBEcGqEacb6oP2KHfHer04WIbAMHZ eduardoefb@efb
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEogQQvxuvrZQZY7mNRxWTQ2KM+BzggtaGbckhevJiOXHbN1TyJZNFXMHz3ZH2g913uXCD31hikSwhWQdGPDCIy8KRPdaDsa9zVhZJ5e/WQ9/g2OYaZDlL1ESQtJvCCubo7XDxHkOPxrjaIJrt8sAJRCBO3GIoY+Ush+tqG7KnGuj3Z9MkunaRmNKmaOrRQtxAhGW0na6mRltdpkdVvSrER1MIh4dipr6CAm79xcdqzq64qkYLPq31AQs8A4B8rIPcZipaxBFi5KARC9PvEJ4pkAvaGFnPmFY1v1FUGSsuF0hRZiqa/gUU1QGKvT2UlA1dvbU6gY2rohilMiDtQOaD eduardoefb@efb
  
  timezone: Brazil/East
  hypervisor:
    name: hypervisor
    ip: 10.2.1.31
    workdir: /srv/magma    

  
  network:
    domain: orc8r.int
    ntp_servers:      
      - 0.centos.pool.ntp.org
      - 1.centos.pool.ntp.org
      - 2.centos.pool.ntp.org
      - 3.centos.pool.ntp.org
      
    oam:
      name: k8s_oam
      external_vlan: 13
      external_interface: eth0
      network: 10.5.0.0
      broadcast: 10.5.0.31
      gateway: 10.5.0.1
      netmask: 255.255.255.224
      netmask_len: 27
      dns: 8.8.8.8
      dev: "vnet0"
      alias: "net0"
      slot: "0x10"
      type: "rtl8139"
      mtu: 1500
 
    external: 
      - name: agw_s1
        external_vlan: 2000
        external_interface: eth0
        network: 10.10.0.0        
        broadcast: 10.10.0.7       
        netmask: 255.255.255.248
        netmask_len: 29
        dev: "vnet1"
        alias: "net1"
        slot: "0x11" 
        type: "rtl8139"   
        mtu: 1500
    
  disk_image: "/srv/image/debian.img"

  common:
    os_disk_size: "40G"
    
  nodes:  

    - name: agw01
      hypervisor: "{{ hypervisor }}"
      ram: 8192000
      cpus: 4      
      disk: 
        - name: "agw01_disk0.qcow2"
          size: "40G"
          dev: "sda"
          unit: 1
          bus: "sata"
      oam_ip: "10.5.0.11"   
      oam_mac: "74:86:91:c5:f9:ae"                                      
      external_ips: 
        - "10.10.0.4"
      vnc: 
        port: 26024         
   
