
- include_vars: "{{ playbook_dir }}/config.yml"      
- include_vars: "main.yml"
  
- name: Get nms hosts
  shell: |  
    kubectl get services nginx-proxy-exposed | grep LoadBalancer | awk '{print $4}'
  args:
    executable: /bin/bash
  register: nmsout

- name: Get controller hosts
  shell: |  
    kubectl get services ssl-http2-legacy | grep LoadBalancer | awk '{print $4}'    
  args:
    executable: /bin/bash
  register: controllerout  

- name: Get controllerint hosts
  shell: |  
    kubectl get services controller | grep ClusterIP | awk '{print $3}'
  args:
    executable: /bin/bash
  register: controllerintout    


- name: Get api hosts
  shell: |  
    kubectl get services clientcert-legacy | grep LoadBalancer | awk '{print $4}'
  args:
    executable: /bin/bash
  register: apiout   
  
- name: Get bootstrapper hosts
  shell: |  
    kubectl get services bootstrap-legacy | grep LoadBalancer | awk '{print $4}'
  args:
    executable: /bin/bash
  register: bootstrapperout   

  
- name: Get fluentd hosts
  shell: |  
    kubectl get service fluentd-exposed | grep LoadBalancer | awk '{print $4}'
  args:
    executable: /bin/bash
  register: fluentdout     

- set_fact:
    nms={{ nmsout.stdout }}
    controller={{ controllerout.stdout }}
    controllerint={{ controllerout.stdout }}
    api={{ apiout.stdout }}
    bootstrapper={{ bootstrapperout.stdout }}
    fluentd={{ fluentdout.stdout }}

- name: Create hostnames file
  template:
    src: hostnames.j2
    dest: "{{ playbook_dir }}/hostnames.yml"
  vars:
    - nms: "{{ nms }}"
    - controller: "{{ controller }}"
    - controllerint: "{{ controllerint }}"
    - api: "{{ api }}"
    - bootstrapper: "{{ bootstrapper }}"
    - fluentd: "{{ fluentd }}"

- name: Create etc_hosts file
  template:
    src: etc_hosts.j2
    dest: "{{ playbook_dir }}/etc_hosts"
  vars:
    - nms: "{{ nms }}"
    - controller: "{{ controller }}"
    - controllerint: "{{ controllerint }}"
    - api: "{{ api }}"
    - bootstrapper: "{{ bootstrapper }}"
    - fluentd: "{{ fluentd }}"    
    

