apiVersion: v1
kind: PersistentVolume
metadata:
  name: magmalte-claim2
  labels:
    type: local
spec:  
  capacity:
    storage: 100Mi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: magmalte-claim2
    namespace: default      
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/k8s_volume/magmalte-claim2
    server: {{ .Values.nfs.ip }}
