apiVersion: v1
kind: PersistentVolume
metadata:
  name: nmsdb
  labels:
    type: local
spec:  
  capacity:
    storage: 1000Mi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: nmsdb
    namespace: default       
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/node01/magmalte-claim0"
