---
  - include_vars: "{{ playbook_dir }}/config.yml"      
  - include_vars: "main.yml"

  - name: Add repos
    shell: |
      apt install git -y
      git config --global user.name "Laurent"
      git config --global user.email "laurent.thomas@open-cells.com"
      echo -n | openssl s_client -showcerts -connect gitlab.eurecom.fr:443 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt
    args:
      executable: /bin/bash
      warn: no

  - name: Install USRP drivers
    shell: |
      apt-get install libboost-all-dev libusb-1.0-0-dev python-mako doxygen python-docutils python-requests python3-pip cmake build-essential -y
      pip3 install mako numpy
      git clone git://github.com/EttusResearch/uhd.git
      cd uhd; mkdir host/build; cd host/build
      cmake -DCMAKE_INSTALL_PREFIX=/usr ..
      make -j4
      make install
      ldconfig
      /usr/lib/uhd/utils/uhd_images_downloader.py
      cd /root/
      git clone https://gitlab.eurecom.fr/oai/openairinterface5g.git
      cd openairinterface5g
      git checkout develop
      source oaienv
      ./cmake_targets/build_oai -I  # install SW packages from internet
      ./cmake_targets/build_oai -w USRP --eNB --UE # compile eNB and UE
      cd /root/
      wget https://open-cells.com/opencells-mods-20190923.tgz
      tar xf opencells-mods-20190923.tgz

    args:
      executable: /bin/bash
      warn: no



