---
  - include_vars: "{{ playbook_dir }}/config.yml"      
  - include_vars: "main.yml"

  - name: Configure enodeb
    template: 
      src: enodeb.conf.j2
      dest: /root/opencells-mods/enb.sample
      owner: root 
      group: root 
      mode: '744'
      
  - name: Create script 
    template:
      src: connect.sh.j2
      dest: /usr/local/bin/connect_to_mme.sh
      mode: '755'
    

      