- 
   name: Prepare NFS server
   hosts: MASTER01
   remote_user: root
   tasks:
      - name: NFS Server 01
        shell:                  
          rm -rf /srv/k8s_volume/*;          
          mkdir -pv /srv/k8s_volume/elasticsearch;
          chmod -R 775 /srv/k8s_volume/elasticsearch;                  
          mkdir /srv/k8s_volume/alertmanager-configurer-claim0;              
          mkdir /srv/k8s_volume/alertmanager-claim0;
          mkdir /srv/k8s_volume/prometheus-claim0;
          mkdir /srv/k8s_volume/prometheus-configurer-claim0;
          
          rm -rfv /root/magma 2>/dev/null;
          rm -f /root/v1.1.0.tar.gz 2>/dev/null;
          wget https://github.com/magma/magma/archive/v1.1.0.tar.gz -O /root/v1.1.0.tar.gz;
          tar -xvf v1.1.0.tar.gz -C /root/;
          mv /root/magma-1.1.0 /root/magma;
          cp -rfv /root/magma/symphony/app/fbcnms-packages /srv/k8s_volume/magmalte-claim0;
          ls -lhtr /srv/k8s_volume/magmalte-claim0;
          cp -rfv /root/magma/symphony/app/fbcnms-projects/magmalte/app /srv/k8s_volume/magmalte-claim1;
          ls -lhtr /srv/k8s_volume/magmalte-claim1;
          cp -rfv /root/magma/symphony/app/fbcnms-projects/magmalte/scripts/ /srv/k8s_volume/magmalte-claim2;
          ls -lhtr /srv/k8s_volume/magmalte-claim2;
          cp -rfv /root/magma/symphony/app/fbcnms-projects/magmalte/server/ /srv/k8s_volume/magmalte-claim3;
          ls -lhtr /srv/k8s_volume/magmalte-claim3;
          rm -rf /root/magma 2>/dev/null;
          rm -f /root/v1.1.0.tar.gz 2>/dev/null          ;

        args:
           warn: no

      - name: Copy alertmanager-configurer configuration file
        copy:
           src: /tmp/alertmanager.yml
           dest: /srv/k8s_volume/alertmanager-configurer-claim0/alertmanager.yml

      - name: Copy alertmanager configuration file
        copy:
           src: /tmp/alertmanager.yml
           dest: /srv/k8s_volume/alertmanager-claim0/alertmanager.yml
           
      - name: Copy prometheus configuration file
        copy:
           src: /tmp/prometheus.yml
           dest: /srv/k8s_volume/prometheus-claim0/prometheus.yml

      - name: Copy prometheus-configurer configuration file
        copy:
           src: /tmp/prometheus-configurer.yml
           dest: /srv/k8s_volume/prometheus-configurer-claim0/prometheus.yml  
                      
      - name: Grafana configuration files
        shell:
          docker run --name=tmp_grafana -t -d grafana/grafana:6.6.2;
          docker cp tmp_grafana:/var/lib/grafana /srv/k8s_volume/user-grafana/;
          chmod -R 777 /srv/k8s_volume/user-grafana/;
          docker stop tmp_grafana;
          docker rm tmp_grafana;
        args:
           warn: no
