apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch
  labels:
    type: local
spec:  
  capacity:
    storage: 100Mi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: elasticsearch
    namespace: default       
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/node01/elasticsearch"
