apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: alertmanager
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: alertmanager
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: alertmanager
    spec:
      containers:
      - image: prom/alertmanager
        imagePullPolicy: ""
        name: alertmanager
        ports:
        - containerPort: 9093
        resources: {}
        volumeMounts:
        - mountPath: /etc/alertmanager
          name: alertmanager-claim0
          readOnly: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: alertmanager-claim0
        persistentVolumeClaim:
          claimName: alertmanager-claim0
          readOnly: true
status: {}
