apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-claim0
  labels:
    type: local
spec:  
  capacity:
    storage: 100Mi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: alertmanager-claim0
    namespace: default    
  accessModes:
    - ReadOnlyMany 
  hostPath:
    path: "/media/node01/alertmanager-claim0"
