apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: alertmanager-configurer
  name: alertmanager-configurer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: alertmanager-configurer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: alertmanager-configurer
    spec:
      containers:
      - args:
        - -port=9101
        - -alertmanager-conf=/etc/configs/alertmanager.yml
        - -alertmanagerURL=alertmanager:9093
        - -multitenant-label=networkID
        image: facebookincubator/alertmanager-configurer:1.0.0
        imagePullPolicy: ""
        name: alertmanager-configurer
        resources: {}
        volumeMounts:
        - mountPath: /etc/configs
          name: alertmanager-configurer-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: alertmanager-configurer-claim0
        persistentVolumeClaim:
          claimName: alertmanager-configurer-claim0
      imagePullSecrets:
      - name: regcred          
status: {}
