apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: controller
  name: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: controller
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: controller
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - echo "#PSQL_HA_IP# postgres" >> /etc/hosts && /usr/local/bin/wait-for-it.sh -s -t 30 postgres:5432 && /usr/bin/supervisord
        env:
        - name: DATABASE_SOURCE
          valueFrom:
            secretKeyRef:
              name: controller
              key: DATABASE_SOURCE
        - name: SQL_DIALECT
          value: psql
        - name: SQL_DRIVER
          value: postgres
        - name: SERVICE_HOST_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: HOST_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP

        image: #REGISTERY#/controller:1.3.0-master
        imagePullPolicy: ""
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 9079
          protocol: TCP
        - containerPort: 9080
          protocol: TCP
        - containerPort: 9081
          protocol: TCP
        - containerPort: 9082
          protocol: TCP
        - containerPort: 9083
          protocol: TCP
        - containerPort: 9084
          protocol: TCP
        - containerPort: 9085
          protocol: TCP
        - containerPort: 9086
          protocol: TCP
        - containerPort: 9087
          protocol: TCP
        - containerPort: 9088
          protocol: TCP
        - containerPort: 9089
          protocol: TCP
        - containerPort: 9090
          protocol: TCP
        - containerPort: 9091
          protocol: TCP
        - containerPort: 9092
          protocol: TCP
        - containerPort: 9093
          protocol: TCP
        - containerPort: 9094
          protocol: TCP
        - containerPort: 9095
          protocol: TCP
        - containerPort: 9096
          protocol: TCP
        - containerPort: 9097
          protocol: TCP
        - containerPort: 9098
          protocol: TCP
        - containerPort: 9099
          protocol: TCP
        - containerPort: 9100
          protocol: TCP
        - containerPort: 9101
          protocol: TCP
        - containerPort: 9102
          protocol: TCP
        - containerPort: 9103
          protocol: TCP
        - containerPort: 9104
          protocol: TCP
        - containerPort: 9105
          protocol: TCP
        - containerPort: 9106
          protocol: TCP
        - containerPort: 9107
          protocol: TCP
        - containerPort: 9108
          protocol: TCP
        name: controller
        resources: {}
        volumeMounts:
        - mountPath: /var/opt/magma/certs
          name: certs
          readOnly: true          
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: certs
        secret:
          defaultMode: 420
          secretName: orc8r-certs
      imagePullSecrets:
      - name: regcred
status: {}
