apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-claim0
  labels:
    type: local
spec:  
  capacity:
    storage: 100Mi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: prometheus-claim0
    namespace: default    
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/media/node01/prometheus-claim0"
