
- include_vars: "{{ playbook_dir }}/config.yml"      
- include_vars: "main.yml"
   
- name: Preparing upload script
  template:
    src: upload.sh.j2
    dest: /tmp/upload.sh
    mode: '744'
    owner: root
    group: root

- name: Upload images
  shell: |
    bash -x /tmp/upload.sh
  args:
    executable: /bin/bash