
- include_vars: "{{ playbook_dir }}/config.yml"      
- include_vars: "main.yml"
   
- name: Preparing upload script
  template:
    src: upload.sh.j2
    dest: /tmp/upload.sh
    mode: '744'
    owner: root
    group: root

- name: Allow registery url
  template:
    src: docker.json.j2
    dest: /etc/docker/daemon.json 


- name: Delete dir 
  file:
    state: absent
    path: /root/certs
    
- name: Create dir 
  file:
    state: directory
    path: /root/certs
    owner: root
    group: root
    mode: '0644'

- name: Transfer files
  copy:
    src: "{{ playbook_dir }}/registry_certs/regca.crt"     
    dest: /root/certs/regca.crt
    mode: '0644'
    owner: root 
    group: root    
    
- name: Transfer key
  copy:
    src: "{{ playbook_dir }}/registry_certs/{{magma.registry.host }}.{{ magma.domain }}.key"     
    dest: /root/certs/{{magma.registry.host }}.{{ magma.domain }}.key
    mode: '0700'
    owner: root 
    group: root    

- name: Transfer crt
  copy:
    src: "{{ playbook_dir }}/registry_certs/{{magma.registry.host }}.{{ magma.domain }}.crt"     
    dest: /root/certs/{{magma.registry.host }}.{{ magma.domain }}.crt
    mode: '0700'
    owner: root 
    group: root 

- name: Upload images
  shell: |
    bash -x /tmp/upload.sh
  args:
    executable: /bin/bash