# Create everything
- hosts: hypervisor
  user: cloud
  become: true
  roles:     
    - role: 04_create_vms

# Update nodes:
- hosts: nodes
  user: cloud
  become: true
  roles:     
    - role: 05_update
